apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-1-ingress
spec:
  rules:
  - host: minikube.local
    http:
      paths:
      - pathType: Prefix
        path: "/app1"
        backend:
          service:
            name: app-1-service
            port:
              number: 3000