apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    upstream backend {
    server app-1-service:80;
    server app-2-service:80;
    }

    server {
        location / {
            proxy_pass http://backend;
        }
    }
